version: '3.1'

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: unless-stopped
    volumes: #data directory, database directory, json directory
      - /opt/filebrowser:/srv
      - /opt/filebrowser/database/filebrowser.db:/database.db 
      - /opt/filebrowser/config/filebrowser.json:/filebrowser.json
    ports:
      - 8080:80
    restart: unless-stopped
