version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    user: 1000:1000
    ports:
      - 8888:80
    volumes:
      - /media/md0/data/:/srv
      - /media/md0/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
